name: repocopy build release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: thevlang/vlang:alpine

    steps:
    - uses: actions/checkout@v3
    - run: v test .
    # FIXME(hholst): -fno-inline-small-functions is required or the build will break with -prod
    - run: v -prod -cc gcc -cflags -fno-inline-small-functions -cflags -static -o repocopy .
    - run: strip repocopy
    - uses: softprops/action-gh-release@v1
      with:
        files: repocopy
